"""initial schema — 7 tables (R1 PR #5)

Revision ID: 001_initial_schema
Revises:
Create Date: 2026-04-17 16:33:16.314453+00:00

Creates the complete persistence schema for the v2 architecture:
    - positions, position_snapshots, trades, account_snaps  (R1 PR #3)
    - vol_surfaces, signals, backtest_runs                   (R1 PR #4)

Indices and GIN on JSONB land in a separate migration (R1 PR #6).
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "001_initial_schema"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_snaps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('net_liq_usd', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('cash_usd', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('buying_power_usd', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('available_usd', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('unrealized_pnl_usd', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('realized_pnl_usd', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('gross_position_value_usd', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('currencies', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('open_positions_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('backtest_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_name', sa.String(length=50), nullable=False),
    sa.Column('parameters', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('sharpe_ratio', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('sortino_ratio', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('max_drawdown_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('max_drawdown_duration_days', sa.Integer(), nullable=True),
    sa.Column('hit_rate', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('total_return_pct', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('annualized_return_pct', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('annualized_vol_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('n_trades', sa.Integer(), nullable=True),
    sa.Column('avg_holding_period_days', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('profit_factor', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('equity_curve', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('trades_log', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('instrument_type', sa.String(length=10), nullable=False),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('strike', sa.Numeric(precision=10, scale=5), nullable=True),
    sa.Column('maturity', sa.Date(), nullable=True),
    sa.Column('option_type', sa.String(length=4), nullable=True),
    sa.Column('entry_price', sa.Numeric(precision=15, scale=8), nullable=False),
    sa.Column('entry_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('exit_price', sa.Numeric(precision=15, scale=8), nullable=True),
    sa.Column('exit_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("instrument_type IN ('SPOT', 'FUTURE', 'OPTION')", name='ck_positions_instrument_type'),
    sa.CheckConstraint("option_type IS NULL OR option_type IN ('CALL', 'PUT')", name='ck_positions_option_type'),
    sa.CheckConstraint("side IN ('BUY', 'SELL')", name='ck_positions_side'),
    sa.CheckConstraint("status IN ('OPEN', 'CLOSED', 'EXPIRED')", name='ck_positions_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('underlying', sa.String(length=20), nullable=False),
    sa.Column('tenor', sa.String(length=5), nullable=False),
    sa.Column('dte', sa.Integer(), nullable=False),
    sa.Column('sigma_mid', sa.Numeric(precision=8, scale=5), nullable=False),
    sa.Column('sigma_fair', sa.Numeric(precision=8, scale=5), nullable=False),
    sa.Column('ecart', sa.Numeric(precision=8, scale=5), nullable=False),
    sa.Column('signal_type', sa.String(length=15), nullable=False),
    sa.Column('rv', sa.Numeric(precision=8, scale=5), nullable=True),
    sa.CheckConstraint("signal_type IN ('CHEAP', 'EXPENSIVE', 'FAIR')", name='ck_signals_signal_type'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('timestamp', 'underlying', 'tenor', name='uq_signals_ts_underlying_tenor')
    )
    op.create_table('vol_surfaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('underlying', sa.String(length=20), nullable=False),
    sa.Column('spot', sa.Numeric(precision=15, scale=8), nullable=False),
    sa.Column('forward', sa.Numeric(precision=15, scale=8), nullable=True),
    sa.Column('surface_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('fair_vol_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('rv_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('scan_duration_s', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('timestamp', 'underlying', name='uq_vol_surfaces_ts_underlying')
    )
    op.create_table('position_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('spot', sa.Numeric(precision=15, scale=8), nullable=True),
    sa.Column('iv', sa.Numeric(precision=8, scale=5), nullable=True),
    sa.Column('delta_usd', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('vega_usd', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('gamma_usd', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('theta_usd', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('pnl_usd', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.Column('ib_order_id', sa.String(length=50), nullable=True),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('price', sa.Numeric(precision=15, scale=8), nullable=False),
    sa.Column('commission', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('spot_at_execution', sa.Numeric(precision=15, scale=8), nullable=True),
    sa.Column('iv_at_execution', sa.Numeric(precision=8, scale=5), nullable=True),
    sa.CheckConstraint("side IN ('BUY', 'SELL')", name='ck_trades_side'),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ib_order_id', name='uq_trades_ib_order_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trades')
    op.drop_table('position_snapshots')
    op.drop_table('vol_surfaces')
    op.drop_table('signals')
    op.drop_table('positions')
    op.drop_table('backtest_runs')
    op.drop_table('account_snaps')
    # ### end Alembic commands ###
