"""add col X — accidental autogen artifact, retained for chain integrity.

⚠ HISTORICAL NOTE FOR FUTURE READERS

This file is a leftover from a misfired ``alembic revision --autogenerate``
early in the project (April 2026). Its name suggests an "add column"
intent, but the actual upgrade simply **drops the 16 indexes that
migration 002 had just created** — then migration 003 immediately re-
creates the same indexes alongside its own schema additions.

Net effect : zero. The DROP+CREATE round-trip cancels itself.

Why this file is still here :

  - At the time of detection (R10 DB review), the chain
    ``002 → 254fc54bb36f → 003`` was already applied in every deployed
    DB.
  - Deleting the file would orphan ``003``'s ``down_revision``
    reference and break ``alembic upgrade`` on any fresh DB.
  - Editing the revision ID would break the in-DB ``alembic_version``
    history on every existing deployment.

So the file stays. The hash filename (rather than a descriptive name)
plus the misleading ``add col X`` title are part of the audit trail
that this autogen actually ran. The contents below are intentionally
untouched.

If a future migration absolutely needs to clean this up, the right
move is :

  1. New migration ``NNN_collapse_002_254fc54bb36f.py`` that does
     nothing on upgrade (DB is already in the correct state) but on
     downgrade replays the 254fc54bb36f drops to keep the rollback
     path symmetric.
  2. Update ``003``'s ``down_revision`` to point at ``002`` directly,
     drop this file.
  3. ``alembic stamp NNN`` on every deployed DB during a maintenance
     window.

Until then : **do not edit, do not delete**.

Revision ID: 254fc54bb36f
Revises: 002_add_indices
Create Date: 2026-04-21 08:57:43.366204+00:00
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '254fc54bb36f'
down_revision: str | None = '002_add_indices'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_account_ts', table_name='account_snaps')
    op.drop_index('idx_backtest_created', table_name='backtest_runs')
    op.drop_index('idx_backtest_strategy', table_name='backtest_runs')
    op.drop_index('idx_pos_snaps_position_ts', table_name='position_snapshots')
    op.drop_index('idx_pos_snaps_ts', table_name='position_snapshots')
    op.drop_index('idx_positions_entry_ts', table_name='positions')
    op.drop_index('idx_positions_status_active', table_name='positions', postgresql_where="((status)::text = 'OPEN'::text)")
    op.drop_index('idx_positions_symbol_status', table_name='positions')
    op.drop_index('idx_signals_ts', table_name='signals')
    op.drop_index('idx_signals_type_ts', table_name='signals')
    op.drop_index('idx_signals_underlying_tenor_ts', table_name='signals')
    op.drop_index('idx_trades_position', table_name='trades')
    op.drop_index('idx_trades_ts', table_name='trades')
    op.drop_index('idx_vol_surf_data_gin', table_name='vol_surfaces', postgresql_using='gin')
    op.drop_index('idx_vol_surf_ts', table_name='vol_surfaces')
    op.drop_index('idx_vol_surf_underlying_ts', table_name='vol_surfaces')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_vol_surf_underlying_ts', 'vol_surfaces', ['underlying', sa.text('timestamp DESC')], unique=False)
    op.create_index('idx_vol_surf_ts', 'vol_surfaces', [sa.text('timestamp DESC')], unique=False)
    op.create_index('idx_vol_surf_data_gin', 'vol_surfaces', ['surface_data'], unique=False, postgresql_using='gin')
    op.create_index('idx_trades_ts', 'trades', [sa.text('timestamp DESC')], unique=False)
    op.create_index('idx_trades_position', 'trades', ['position_id'], unique=False)
    op.create_index('idx_signals_underlying_tenor_ts', 'signals', ['underlying', 'tenor', sa.text('timestamp DESC')], unique=False)
    op.create_index('idx_signals_type_ts', 'signals', ['signal_type', sa.text('timestamp DESC')], unique=False)
    op.create_index('idx_signals_ts', 'signals', [sa.text('timestamp DESC')], unique=False)
    op.create_index('idx_positions_symbol_status', 'positions', ['symbol', 'status'], unique=False)
    op.create_index('idx_positions_status_active', 'positions', ['status'], unique=False, postgresql_where="((status)::text = 'OPEN'::text)")
    op.create_index('idx_positions_entry_ts', 'positions', [sa.text('entry_timestamp DESC')], unique=False)
    op.create_index('idx_pos_snaps_ts', 'position_snapshots', [sa.text('timestamp DESC')], unique=False)
    op.create_index('idx_pos_snaps_position_ts', 'position_snapshots', ['position_id', sa.text('timestamp DESC')], unique=False)
    op.create_index('idx_backtest_strategy', 'backtest_runs', ['strategy_name'], unique=False)
    op.create_index('idx_backtest_created', 'backtest_runs', [sa.text('created_at DESC')], unique=False)
    op.create_index('idx_account_ts', 'account_snaps', [sa.text('timestamp DESC')], unique=False)
    # ### end Alembic commands ###
