"""add col X

Revision ID: 254fc54bb36f
Revises: 002_add_indices
Create Date: 2026-04-21 08:57:43.366204+00:00

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '254fc54bb36f'
down_revision: str | None = '002_add_indices'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_account_ts', table_name='account_snaps')
    op.drop_index('idx_backtest_created', table_name='backtest_runs')
    op.drop_index('idx_backtest_strategy', table_name='backtest_runs')
    op.drop_index('idx_pos_snaps_position_ts', table_name='position_snapshots')
    op.drop_index('idx_pos_snaps_ts', table_name='position_snapshots')
    op.drop_index('idx_positions_entry_ts', table_name='positions')
    op.drop_index('idx_positions_status_active', table_name='positions', postgresql_where="((status)::text = 'OPEN'::text)")
    op.drop_index('idx_positions_symbol_status', table_name='positions')
    op.drop_index('idx_signals_ts', table_name='signals')
    op.drop_index('idx_signals_type_ts', table_name='signals')
    op.drop_index('idx_signals_underlying_tenor_ts', table_name='signals')
    op.drop_index('idx_trades_position', table_name='trades')
    op.drop_index('idx_trades_ts', table_name='trades')
    op.drop_index('idx_vol_surf_data_gin', table_name='vol_surfaces', postgresql_using='gin')
    op.drop_index('idx_vol_surf_ts', table_name='vol_surfaces')
    op.drop_index('idx_vol_surf_underlying_ts', table_name='vol_surfaces')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_vol_surf_underlying_ts', 'vol_surfaces', ['underlying', sa.text('timestamp DESC')], unique=False)
    op.create_index('idx_vol_surf_ts', 'vol_surfaces', [sa.text('timestamp DESC')], unique=False)
    op.create_index('idx_vol_surf_data_gin', 'vol_surfaces', ['surface_data'], unique=False, postgresql_using='gin')
    op.create_index('idx_trades_ts', 'trades', [sa.text('timestamp DESC')], unique=False)
    op.create_index('idx_trades_position', 'trades', ['position_id'], unique=False)
    op.create_index('idx_signals_underlying_tenor_ts', 'signals', ['underlying', 'tenor', sa.text('timestamp DESC')], unique=False)
    op.create_index('idx_signals_type_ts', 'signals', ['signal_type', sa.text('timestamp DESC')], unique=False)
    op.create_index('idx_signals_ts', 'signals', [sa.text('timestamp DESC')], unique=False)
    op.create_index('idx_positions_symbol_status', 'positions', ['symbol', 'status'], unique=False)
    op.create_index('idx_positions_status_active', 'positions', ['status'], unique=False, postgresql_where="((status)::text = 'OPEN'::text)")
    op.create_index('idx_positions_entry_ts', 'positions', [sa.text('entry_timestamp DESC')], unique=False)
    op.create_index('idx_pos_snaps_ts', 'position_snapshots', [sa.text('timestamp DESC')], unique=False)
    op.create_index('idx_pos_snaps_position_ts', 'position_snapshots', ['position_id', sa.text('timestamp DESC')], unique=False)
    op.create_index('idx_backtest_strategy', 'backtest_runs', ['strategy_name'], unique=False)
    op.create_index('idx_backtest_created', 'backtest_runs', [sa.text('created_at DESC')], unique=False)
    op.create_index('idx_account_ts', 'account_snaps', [sa.text('timestamp DESC')], unique=False)
    # ### end Alembic commands ###
