blank_issues_enabled: false
contact_links:
  - name: Questions / Help
    url: https://github.com/valerian-drmtt/Trading_Project/discussions
    about: "Ask questions or discuss ideas in Discussions"
