/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness probe — always 200 as long as the FastAPI process answers.
         */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/extended": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Extended
         * @description Readiness probe — Redis + DB + engine heartbeats. Aggregate status.
         *
         *     Status is ``DEGRADED`` if any subsystem is not OK, else ``OK``.
         *     Redis heartbeats are the authoritative engine liveness signal
         *     (written by the engines every ~1s via ``set_heartbeat``).
         */
        get: operations["health_extended_api_v1_health_extended_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/price": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Price */
        post: operations["price_api_v1_price_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/greeks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Greeks */
        post: operations["greeks_api_v1_greeks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/iv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Implied Vol
         * @description Invert BS → implied vol. 422 if market_price falls outside the bracket.
         */
        post: operations["implied_vol_api_v1_iv_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vol/surface": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Latest Surface
         * @description Latest volatility surface for ``symbol`` — reads Redis cache (TTL 600s).
         */
        get: operations["latest_surface_api_v1_vol_surface_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vol/surface/at/{ts}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Surface At
         * @description Historical surface at exact timestamp — reads Postgres ``vol_surfaces``.
         */
        get: operations["surface_at_api_v1_vol_surface_at__ts__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vol/term-structure": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Term Structure
         * @description Tenor → ATM vol mapping derived from the latest Redis surface.
         */
        get: operations["term_structure_api_v1_vol_term_structure_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vol/smile/{tenor}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Smile
         * @description 5-point smile (10P/25P/ATM/25C/10C) for a tenor from the latest PG row.
         */
        get: operations["smile_api_v1_vol_smile__tenor__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/positions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Positions
         * @description All positions (most-recent first). Filter by ``status`` if given.
         */
        get: operations["list_positions_api_v1_positions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/positions/{position_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Position */
        get: operations["get_position_api_v1_positions__position_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/risk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Portfolio Risk
         * @description Portfolio-level greeks published by RiskEngine every cycle (~2s).
         */
        get: operations["portfolio_risk_api_v1_risk_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pnl-curve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Pnl Curve */
        get: operations["pnl_curve_api_v1_pnl_curve_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Position History
         * @description Snapshots for a position, oldest-first (ready for timeseries plotting).
         */
        get: operations["position_history_api_v1_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/signals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Signals
         * @description Recent signals, most-recent first. Filters combinable (underlying, tenor, type, since).
         */
        get: operations["signals_api_v1_signals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vol-history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Vol History
         * @description N most recent vol_surfaces snapshots — headline fields only (no JSONB payload).
         */
        get: operations["vol_history_api_v1_vol_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/backtest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Backtests
         * @description Backtest runs with headline metrics (Sharpe, MDD, return, n_trades).
         */
        get: operations["backtests_api_v1_backtest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system-stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * System Stats
         * @description Combined view : PG row counts + engine heartbeat ages from Redis.
         */
        get: operations["system_stats_api_v1_system_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * BacktestRunRow
         * @description One row of backtest_runs — headline metrics only.
         */
        BacktestRunRow: {
            /** Id */
            id: number;
            /** Strategy Name */
            strategy_name: string;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /**
             * End Date
             * Format: date
             */
            end_date: string;
            /** Sharpe Ratio */
            sharpe_ratio: string | null;
            /** Max Drawdown Pct */
            max_drawdown_pct: string | null;
            /** Total Return Pct */
            total_return_pct: string | null;
            /** N Trades */
            n_trades: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** EngineStats */
        EngineStats: {
            /** Name */
            name: string;
            /** State */
            state: string;
            /** Heartbeat Age S */
            heartbeat_age_s: number | null;
        };
        /**
         * GreeksAggregated
         * @description Portfolio-level greeks as published by RiskEngine to Redis.
         */
        GreeksAggregated: {
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Greeks */
            greeks: {
                [key: string]: unknown;
            };
        };
        /**
         * GreeksRequest
         * @description Same shape as PriceRequest — alias kept for OpenAPI clarity.
         */
        GreeksRequest: {
            /**
             * Spot
             * @description Forward price (F) used in BS formula
             */
            spot: number;
            /**
             * Strike
             * @description Option strike
             */
            strike: number;
            /**
             * Maturity Days
             * @description Days to expiry (capped 10y)
             */
            maturity_days: number;
            /**
             * Option Type
             * @default CALL
             * @enum {string}
             */
            option_type: "CALL" | "PUT";
            /**
             * Volatility
             * @description Annualized vol in decimal form (0.075 = 7.5%)
             */
            volatility: number;
        };
        /** GreeksResponse */
        GreeksResponse: {
            /** Price */
            price: number;
            /** Delta */
            delta: number;
            /** Gamma */
            gamma: number;
            /** Vega */
            vega: number;
            /** Theta */
            theta: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HistoryResponse */
        HistoryResponse: {
            /** Position Id */
            position_id: number;
            /** Snapshots */
            snapshots: components["schemas"]["PositionSnapshotView"][];
        };
        /**
         * ImpliedVolRequest
         * @description Invert BS from a market price to get the implied vol.
         */
        ImpliedVolRequest: {
            /**
             * Spot
             * @description Forward price (F) used in BS formula
             */
            spot: number;
            /**
             * Strike
             * @description Option strike
             */
            strike: number;
            /**
             * Maturity Days
             * @description Days to expiry (capped 10y)
             */
            maturity_days: number;
            /**
             * Option Type
             * @default CALL
             * @enum {string}
             */
            option_type: "CALL" | "PUT";
            /**
             * Market Price
             * @description Observed market price of the option
             */
            market_price: number;
        };
        /** ImpliedVolResponse */
        ImpliedVolResponse: {
            /** Implied Volatility */
            implied_volatility: number;
        };
        /**
         * PnLCurve
         * @description Spot vs PnL curve (~31 points) from RiskEngine.
         */
        PnLCurve: {
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Curve */
            curve: {
                [key: string]: unknown;
            };
        };
        /**
         * PositionSnapshotView
         * @description One snapshot row used by /history.
         */
        PositionSnapshotView: {
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Spot */
            spot: string | null;
            /** Iv */
            iv: string | null;
            /** Delta Usd */
            delta_usd: string | null;
            /** Vega Usd */
            vega_usd: string | null;
            /** Gamma Usd */
            gamma_usd: string | null;
            /** Theta Usd */
            theta_usd: string | null;
            /** Pnl Usd */
            pnl_usd: string | null;
        };
        /**
         * PositionView
         * @description A single position row — mirrors ``persistence.models.Position``.
         */
        PositionView: {
            /** Id */
            id: number;
            /** Symbol */
            symbol: string;
            /** Instrument Type */
            instrument_type: string;
            /** Side */
            side: string;
            /** Quantity */
            quantity: string;
            /** Strike */
            strike: string | null;
            /** Maturity */
            maturity: string | null;
            /** Option Type */
            option_type: string | null;
            /** Entry Price */
            entry_price: string;
            /**
             * Entry Timestamp
             * Format: date-time
             */
            entry_timestamp: string;
            /** Status */
            status: string;
        };
        /**
         * PriceRequest
         * @description Ask for a BS price given (F, K, T, sigma, right).
         */
        PriceRequest: {
            /**
             * Spot
             * @description Forward price (F) used in BS formula
             */
            spot: number;
            /**
             * Strike
             * @description Option strike
             */
            strike: number;
            /**
             * Maturity Days
             * @description Days to expiry (capped 10y)
             */
            maturity_days: number;
            /**
             * Option Type
             * @default CALL
             * @enum {string}
             */
            option_type: "CALL" | "PUT";
            /**
             * Volatility
             * @description Annualized vol in decimal form (0.075 = 7.5%)
             */
            volatility: number;
        };
        /** PriceResponse */
        PriceResponse: {
            /** Price */
            price: number;
        };
        /**
         * SignalRow
         * @description One row of the signals table — one scan's CHEAP/FAIR/EXPENSIVE verdict.
         */
        SignalRow: {
            /** Id */
            id: number;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Underlying */
            underlying: string;
            /** Tenor */
            tenor: string;
            /** Dte */
            dte: number;
            /** Sigma Mid */
            sigma_mid: string;
            /** Sigma Fair */
            sigma_fair: string;
            /** Ecart */
            ecart: string;
            /** Signal Type */
            signal_type: string;
            /** Rv */
            rv: string | null;
        };
        /**
         * SmilePoint
         * @description One point of the smile : strike + implied vol in percent.
         */
        SmilePoint: {
            /** Strike */
            strike: number;
            /** Iv Pct */
            iv_pct: number;
            /** Delta Label */
            delta_label: string;
        };
        /** SmileResponse */
        SmileResponse: {
            /** Symbol */
            symbol: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Tenor */
            tenor: string;
            /** Dte */
            dte: number | null;
            /** Points */
            points: components["schemas"]["SmilePoint"][];
        };
        /**
         * SurfaceResponse
         * @description Latest vol surface for a symbol — pillars keyed by tenor label.
         */
        SurfaceResponse: {
            /** Symbol */
            symbol: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Surface */
            surface: {
                [key: string]: {
                    [key: string]: unknown;
                };
            };
        };
        /**
         * SystemStats
         * @description Portfolio-level stats — counts Postgres + engine heartbeats from Redis.
         */
        SystemStats: {
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Counts */
            counts: {
                [key: string]: number;
            };
            /** Engines */
            engines: components["schemas"]["EngineStats"][];
        };
        /** TermStructureResponse */
        TermStructureResponse: {
            /** Symbol */
            symbol: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Pillars */
            pillars: components["schemas"]["TermStructureRow"][];
        };
        /** TermStructureRow */
        TermStructureRow: {
            /** Tenor */
            tenor: string;
            /** Dte */
            dte: number | null;
            /** Sigma Atm Pct */
            sigma_atm_pct: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * VolHistoryRow
         * @description Lightweight vol surface snapshot — no JSONB payload, just timestamp + F/spot.
         */
        VolHistoryRow: {
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Underlying */
            underlying: string;
            /** Spot */
            spot: string;
            /** Forward */
            forward: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    health_extended_api_v1_health_extended_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    price_api_v1_price_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PriceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PriceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    greeks_api_v1_greeks_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GreeksRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GreeksResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    implied_vol_api_v1_iv_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImpliedVolRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImpliedVolResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    latest_surface_api_v1_vol_surface_get: {
        parameters: {
            query?: {
                symbol?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SurfaceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    surface_at_api_v1_vol_surface_at__ts__get: {
        parameters: {
            query?: {
                symbol?: string;
            };
            header?: never;
            path: {
                ts: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SurfaceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    term_structure_api_v1_vol_term_structure_get: {
        parameters: {
            query?: {
                symbol?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TermStructureResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    smile_api_v1_vol_smile__tenor__get: {
        parameters: {
            query?: {
                symbol?: string;
            };
            header?: never;
            path: {
                tenor: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SmileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_positions_api_v1_positions_get: {
        parameters: {
            query?: {
                status?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PositionView"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_position_api_v1_positions__position_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                position_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PositionView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    portfolio_risk_api_v1_risk_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GreeksAggregated"];
                };
            };
        };
    };
    pnl_curve_api_v1_pnl_curve_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PnLCurve"];
                };
            };
        };
    };
    position_history_api_v1_history_get: {
        parameters: {
            query: {
                position_id: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    signals_api_v1_signals_get: {
        parameters: {
            query?: {
                underlying?: string | null;
                tenor?: string | null;
                signal_type?: string | null;
                since?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignalRow"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    vol_history_api_v1_vol_history_get: {
        parameters: {
            query?: {
                symbol?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VolHistoryRow"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    backtests_api_v1_backtest_get: {
        parameters: {
            query?: {
                strategy_name?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestRunRow"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    system_stats_api_v1_system_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemStats"];
                };
            };
        };
    };
}
