/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness probe — always 200 as long as the FastAPI process answers.
         */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/extended": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Extended
         * @description Readiness probe — Redis + DB + engine heartbeats. Aggregate status.
         *
         *     Status is ``DEGRADED`` if any subsystem is not OK, else ``OK``.
         *     Redis heartbeats are the authoritative engine liveness signal
         *     (written by the engines every ~1s via ``set_heartbeat``).
         */
        get: operations["health_extended_api_v1_health_extended_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/price": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Price */
        post: operations["price_api_v1_price_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/greeks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Greeks */
        post: operations["greeks_api_v1_greeks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/iv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Implied Vol
         * @description Invert BS → implied vol. 422 if market_price falls outside the bracket.
         */
        post: operations["implied_vol_api_v1_iv_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vol/surface": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Latest Surface
         * @description Latest volatility surface for ``symbol`` — reads Redis cache (TTL 600s).
         */
        get: operations["latest_surface_api_v1_vol_surface_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vol/surface/at/{ts}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Surface At
         * @description Historical surface at exact timestamp — reads Postgres ``vol_surfaces``.
         */
        get: operations["surface_at_api_v1_vol_surface_at__ts__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vol/term-structure": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Term Structure
         * @description Tenor → ATM vol mapping derived from the latest Redis surface.
         */
        get: operations["term_structure_api_v1_vol_term_structure_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vol/smile/{tenor}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Smile
         * @description 5-point smile (10P/25P/ATM/25C/10C) for a tenor from the latest PG row.
         */
        get: operations["smile_api_v1_vol_smile__tenor__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/positions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Positions
         * @description All positions (most-recent first). Filter by ``status`` if given.
         */
        get: operations["list_positions_api_v1_positions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/positions/{position_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Position */
        get: operations["get_position_api_v1_positions__position_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/risk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Portfolio Risk
         * @description Portfolio-level greeks published by RiskEngine every cycle (~2s).
         */
        get: operations["portfolio_risk_api_v1_risk_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pnl-curve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Pnl Curve */
        get: operations["pnl_curve_api_v1_pnl_curve_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Position History
         * @description Snapshots for a position, oldest-first (ready for timeseries plotting).
         */
        get: operations["position_history_api_v1_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/signals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Signals
         * @description Recent signals, most-recent first. Filters combinable (underlying, tenor, type, since).
         */
        get: operations["signals_api_v1_signals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vol-history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Vol History
         * @description N most recent vol_surfaces snapshots — headline fields only (no JSONB payload).
         */
        get: operations["vol_history_api_v1_vol_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/backtest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Backtests
         * @description Backtest runs with headline metrics (Sharpe, MDD, return, n_trades).
         */
        get: operations["backtests_api_v1_backtest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system-stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * System Stats
         * @description Combined view : PG row counts + engine heartbeat ages from Redis.
         */
        get: operations["system_stats_api_v1_system_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/regime/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** State */
        get: operations["state_api_v1_regime_state_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/regime/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** History */
        get: operations["history_api_v1_regime_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/regime/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Events */
        get: operations["list_events_api_v1_regime_events_get"];
        put?: never;
        /** Insert Event */
        post: operations["insert_event_api_v1_regime_events_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/regime/transitions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Transitions
         * @description Compte les transitions de label sur les N derniers jours.
         *
         *     But : détecter si le seuil heuristique (vov > 0.4 → pre_event) est trop
         *     proche du bruit de mesure. Si > 5 transitions calm↔pre_event par jour,
         *     c'est un signal pour ajouter de l'hystérésis ou un seuil dynamique
         *     (cf. TODO.md / STEP1 §14).
         *
         *     Returns :
         *       - by_day : dict {YYYY-MM-DD: {transition_type: count}}
         *       - total : sum across all days/transitions
         *       - calm_pre_event_per_day : average flips calm↔pre_event per day
         *       - threshold_warning : True if average > 5/day
         */
        get: operations["transitions_api_v1_regime_transitions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/regime/gmm/shadow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Gmm Shadow Diagnostic
         * @description Compare the shadow GMM outputs vs the active heuristic over the last N
         *     snapshots. Used to decide when the GMM is good enough to take over the
         *     label (cf. STEP1 §13 "switch criteria").
         *
         *     Returns :
         *       - n_with_gmm : number of snapshots where GMM fitted (probabilities not null)
         *       - agreement_ratio : fraction where argmax(p_*) == heuristic label
         *       - cluster_sep_vol_of_vol : (μ_max - μ_min) of components on the vov axis,
         *         a proxy for how distinct the 3 clusters are. Spec §13 requires
         *         > 2 × max(σ_intra) before promoting GMM. We don't have σ_intra
         *         from snapshots ; this number alone is informative on its own.
         *       - by_label : breakdown {heuristic_label: {gmm_argmax: count}}
         *       - ready_to_promote : boolean threshold check
         */
        get: operations["gmm_shadow_diagnostic_api_v1_regime_gmm_shadow_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/regime/events/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sync Events From Feed
         * @description Trigger one full events sync cycle on demand (admin tool).
         *
         *     Same code path as the daily background loop : every configured Source
         *     is hit in parallel with isolation, results are deduped by hash, then
         *     INSERT ON CONFLICT DO NOTHING. Returns the per-source counts so you
         *     can immediately see which sources are healthy.
         */
        post: operations["sync_events_from_feed_api_v1_regime_events_sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/signals/pca/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * State
         * @description Latest 3 signals (1 per PC) under the active PCA model — or, if
         *     ``?scenario=...`` is passed, under the model whose ``version`` matches
         *     the scenario tag (fixture mode).
         */
        get: operations["state_api_v1_signals_pca_state_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/signals/pca/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** History */
        get: operations["history_api_v1_signals_pca_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/signals/pca/model": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Active Model */
        get: operations["active_model_api_v1_signals_pca_model_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/pca/refit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refit
         * @description Manual refit (kept alongside the background scheduler so the user can
         *     force a refit after seeding new data or tweaking thresholds).
         */
        post: operations["refit_api_v1_admin_pca_refit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trade/structures": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Structures */
        get: operations["list_structures_api_v1_trade_structures_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trade/limits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Limits */
        get: operations["list_limits_api_v1_trade_limits_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trade/book": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Book */
        get: operations["get_book_api_v1_trade_book_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trade/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Preview
         * @description Build a full trade preview from a pca_signals.id. Persists to trade_previews
         *     and returns the payload conforming to STEP3 §4.
         */
        post: operations["create_preview_api_v1_trade_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trade/preview/{preview_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Preview */
        get: operations["get_preview_api_v1_trade_preview__preview_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trade/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit Preview
         * @description Step 4 — Submit a previewed trade. **MOCK EXECUTION**.
         *
         *     No IB call is made. Instead the endpoint :
         *       1. Loads the preview row.
         *       2. Creates a ``trade_structures`` row with state='submitted'.
         *       3. Creates ``structure_orders`` rows (one per leg) with state='filled'.
         *       4. Creates ``structure_fills`` rows with synthetic fill prices == preview prices
         *          (zero slippage, $2/contract commission).
         *       5. Marks structure ``fully_filled`` and creates a ``trade_positions`` row.
         *       6. Marks the trade_preview as ``user_action='submitted'``.
         *
         *     Returns the structure summary including position_id. Real IB integration
         *     is deferred to spec phase 2/3.
         */
        post: operations["submit_preview_api_v1_trade_submit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trade/submitted": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Submitted Structures
         * @description List recent submitted trade_structures (for the new positions tab).
         */
        get: operations["list_submitted_structures_api_v1_trade_submitted_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trade/preview/{preview_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Preview */
        post: operations["cancel_preview_api_v1_trade_preview__preview_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Orders */
        get: operations["list_orders_api_v1_orders_get"];
        put?: never;
        /** Place Order */
        post: operations["place_order_api_v1_orders_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{order_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Cancel Order */
        delete: operations["cancel_order_api_v1_orders__order_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exec/positions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live Positions */
        get: operations["live_positions_api_v1_exec_positions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exec/positions/{con_id}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Close Position */
        post: operations["close_position_api_v1_exec_positions__con_id__close_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/positions/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Active
         * @description Union of booked structures (`trade_positions`) and live IB rows
         *     (`positions`). The frontend distinguishes via the ``source`` field
         *     so both lists render in a single Step 5 table.
         */
        get: operations["list_active_api_v1_positions_active_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/positions/aggregate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Aggregate Greeks
         * @description Sum of current greeks across all open positions (for Panel 4 zone B).
         */
        get: operations["aggregate_greeks_api_v1_positions_aggregate_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/positions/exit-rules-config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Exit Rules Config */
        get: operations["list_exit_rules_config_api_v1_positions_exit_rules_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/positions/delta-hedge-config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Delta Hedge Config */
        get: operations["list_delta_hedge_config_api_v1_positions_delta_hedge_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/positions/{position_id}/mtm-history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Mtm History */
        get: operations["mtm_history_api_v1_positions__position_id__mtm_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/positions/{position_id}/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Position Alerts */
        get: operations["position_alerts_api_v1_positions__position_id__alerts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/positions/{position_id}/hedges": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Position Hedges */
        get: operations["position_hedges_api_v1_positions__position_id__hedges_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/positions/{position_id}/signal-tracking": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Signal Tracking */
        get: operations["signal_tracking_api_v1_positions__position_id__signal_tracking_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/positions/{position_id}/close-manual": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Close Manual
         * @description Mark a position for manual close. Step 5 phase 1 = state flip only.
         *
         *     The actual closing-structure submit + fills will be wired when markets-open
         *     phase lands (cf. MARKETS_OPEN_TODO.md). For now we record an audit alert.
         */
        post: operations["close_manual_api_v1_positions__position_id__close_manual_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/positions/monitor/run-once": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Monitor Once
         * @description Trigger one monitoring cycle on demand. Useful from the dev panel.
         *
         *     The scheduler in api lifespan owns the recurring loop ; this endpoint
         *     creates an ad-hoc instance and runs ``run_once`` once.
         */
        post: operations["run_monitor_once_api_v1_positions_monitor_run_once_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * BacktestRunRow
         * @description One row of backtest_runs — headline metrics only.
         */
        BacktestRunRow: {
            /** Id */
            id: number;
            /** Strategy Name */
            strategy_name: string;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /**
             * End Date
             * Format: date
             */
            end_date: string;
            /** Sharpe Ratio */
            sharpe_ratio: string | null;
            /** Max Drawdown Pct */
            max_drawdown_pct: string | null;
            /** Total Return Pct */
            total_return_pct: string | null;
            /** N Trades */
            n_trades: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** EngineStats */
        EngineStats: {
            /** Name */
            name: string;
            /** State */
            state: string;
            /** Heartbeat Age S */
            heartbeat_age_s: number | null;
        };
        /** EventIn */
        EventIn: {
            /** Event Type */
            event_type: string;
            /** Impact */
            impact: string;
            /** Region */
            region: string;
            /**
             * Scheduled At
             * Format: date-time
             */
            scheduled_at: string;
            /** Description */
            description?: string | null;
        };
        /** GateOut */
        GateOut: {
            /** Authorized */
            authorized: boolean;
            /** Reason */
            reason: string;
            /** Size Mult */
            size_mult: number;
        };
        /**
         * GreeksAggregated
         * @description Portfolio-level greeks as published by RiskEngine to Redis.
         */
        GreeksAggregated: {
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Greeks */
            greeks: {
                [key: string]: unknown;
            };
        };
        /**
         * GreeksRequest
         * @description Same shape as PriceRequest — alias kept for OpenAPI clarity.
         */
        GreeksRequest: {
            /**
             * Spot
             * @description Forward price (F) used in BS formula
             */
            spot: number;
            /**
             * Strike
             * @description Option strike
             */
            strike: number;
            /**
             * Maturity Days
             * @description Days to expiry (capped 10y)
             */
            maturity_days: number;
            /**
             * Option Type
             * @default CALL
             * @enum {string}
             */
            option_type: "CALL" | "PUT";
            /**
             * Volatility
             * @description Annualized vol in decimal form (0.075 = 7.5%)
             */
            volatility: number;
        };
        /** GreeksResponse */
        GreeksResponse: {
            /** Price */
            price: number;
            /** Delta */
            delta: number;
            /** Gamma */
            gamma: number;
            /** Vega */
            vega: number;
            /** Theta */
            theta: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HistoryResponse */
        HistoryResponse: {
            /** Position Id */
            position_id: number;
            /** Snapshots */
            snapshots: components["schemas"]["PositionSnapshotView"][];
        };
        /**
         * ImpliedVolRequest
         * @description Invert BS from a market price to get the implied vol.
         */
        ImpliedVolRequest: {
            /**
             * Spot
             * @description Forward price (F) used in BS formula
             */
            spot: number;
            /**
             * Strike
             * @description Option strike
             */
            strike: number;
            /**
             * Maturity Days
             * @description Days to expiry (capped 10y)
             */
            maturity_days: number;
            /**
             * Option Type
             * @default CALL
             * @enum {string}
             */
            option_type: "CALL" | "PUT";
            /**
             * Market Price
             * @description Observed market price of the option
             */
            market_price: number;
        };
        /** ImpliedVolResponse */
        ImpliedVolResponse: {
            /** Implied Volatility */
            implied_volatility: number;
        };
        /** NextEventOut */
        NextEventOut: {
            /** Event Type */
            event_type: string;
            /** Impact */
            impact: string;
            /** Region */
            region: string;
            /**
             * Scheduled At
             * Format: date-time
             */
            scheduled_at: string;
            /** Days Remaining */
            days_remaining: number;
            /** Description */
            description?: string | null;
        };
        /**
         * PnLCurve
         * @description Spot vs PnL curve (~31 points) from RiskEngine.
         */
        PnLCurve: {
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Curve */
            curve: {
                [key: string]: unknown;
            };
        };
        /**
         * PositionSnapshotView
         * @description One snapshot row used by /history.
         */
        PositionSnapshotView: {
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Spot */
            spot: string | null;
            /** Iv */
            iv: string | null;
            /** Delta Usd */
            delta_usd: string | null;
            /** Vega Usd */
            vega_usd: string | null;
            /** Gamma Usd */
            gamma_usd: string | null;
            /** Theta Usd */
            theta_usd: string | null;
            /** Pnl Usd */
            pnl_usd: string | null;
        };
        /**
         * PositionView
         * @description A single position row — mirrors ``persistence.models.Position``.
         */
        PositionView: {
            /** Id */
            id: number;
            /** Symbol */
            symbol: string;
            /** Instrument Type */
            instrument_type: string;
            /** Side */
            side: string;
            /** Quantity */
            quantity: string;
            /** Strike */
            strike: string | null;
            /** Maturity */
            maturity: string | null;
            /** Option Type */
            option_type: string | null;
            /** Entry Price */
            entry_price: string;
            /**
             * Entry Timestamp
             * Format: date-time
             */
            entry_timestamp: string;
            /** Status */
            status: string;
        };
        /** PreviewRequest */
        PreviewRequest: {
            /** Signal Id */
            signal_id?: number | null;
            /** Scenario */
            scenario?: string | null;
            /** Structure Type */
            structure_type?: string | null;
            /** Tenor */
            tenor?: string | null;
            /** Tenor Far */
            tenor_far?: string | null;
            /** Qty */
            qty?: number | null;
            /** Delta Pillar */
            delta_pillar?: string | null;
            /** Strike Override */
            strike_override?: number | null;
            /** Override Tenor */
            override_tenor?: string | null;
            /** Override Far Tenor */
            override_far_tenor?: string | null;
            /** Override Qty */
            override_qty?: number | null;
        };
        /**
         * PriceRequest
         * @description Ask for a BS price given (F, K, T, sigma, right).
         */
        PriceRequest: {
            /**
             * Spot
             * @description Forward price (F) used in BS formula
             */
            spot: number;
            /**
             * Strike
             * @description Option strike
             */
            strike: number;
            /**
             * Maturity Days
             * @description Days to expiry (capped 10y)
             */
            maturity_days: number;
            /**
             * Option Type
             * @default CALL
             * @enum {string}
             */
            option_type: "CALL" | "PUT";
            /**
             * Volatility
             * @description Annualized vol in decimal form (0.075 = 7.5%)
             */
            volatility: number;
        };
        /** PriceResponse */
        PriceResponse: {
            /** Price */
            price: number;
        };
        /** RegimeStateOut */
        RegimeStateOut: {
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Symbol */
            symbol: string;
            /** Label */
            label: string;
            /** Method */
            method: string;
            /** Event Dampener */
            event_dampener: boolean;
            /** Days To Next Event */
            days_to_next_event?: number | null;
            /** Next Event Type */
            next_event_type?: string | null;
            next_event_high?: components["schemas"]["NextEventOut"] | null;
            next_event_any?: components["schemas"]["NextEventOut"] | null;
            /** Features */
            features: {
                [key: string]: {
                    [key: string]: unknown;
                };
            };
            gate: components["schemas"]["GateOut"];
            /** Probabilities */
            probabilities?: {
                [key: string]: number;
            } | null;
        };
        /**
         * SignalRow
         * @description One row of the signals table — one scan's CHEAP/FAIR/EXPENSIVE verdict.
         */
        SignalRow: {
            /** Id */
            id: number;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Underlying */
            underlying: string;
            /** Tenor */
            tenor: string;
            /** Dte */
            dte: number;
            /** Sigma Mid */
            sigma_mid: string;
            /** Sigma Fair */
            sigma_fair: string;
            /** Ecart */
            ecart: string;
            /** Signal Type */
            signal_type: string;
            /** Rv */
            rv: string | null;
        };
        /**
         * SmilePoint
         * @description One point of the smile : strike + implied vol in percent.
         */
        SmilePoint: {
            /** Strike */
            strike: number;
            /** Iv Pct */
            iv_pct: number;
            /** Delta Label */
            delta_label: string;
        };
        /** SmileResponse */
        SmileResponse: {
            /** Symbol */
            symbol: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Tenor */
            tenor: string;
            /** Dte */
            dte: number | null;
            /** Points */
            points: components["schemas"]["SmilePoint"][];
        };
        /**
         * SurfaceResponse
         * @description Latest vol surface for a symbol — pillars keyed by tenor label.
         */
        SurfaceResponse: {
            /** Symbol */
            symbol: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Surface */
            surface: {
                [key: string]: {
                    [key: string]: unknown;
                };
            };
        };
        /**
         * SystemStats
         * @description Portfolio-level stats — counts Postgres + engine heartbeats from Redis.
         */
        SystemStats: {
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Counts */
            counts: {
                [key: string]: number;
            };
            /** Engines */
            engines: components["schemas"]["EngineStats"][];
        };
        /** TermStructureResponse */
        TermStructureResponse: {
            /** Symbol */
            symbol: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Pillars */
            pillars: components["schemas"]["TermStructureRow"][];
        };
        /** TermStructureRow */
        TermStructureRow: {
            /** Tenor */
            tenor: string;
            /** Dte */
            dte: number | null;
            /** Sigma Atm Pct */
            sigma_atm_pct: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * VolHistoryRow
         * @description Lightweight vol surface snapshot — no JSONB payload, just timestamp + F/spot.
         */
        VolHistoryRow: {
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Underlying */
            underlying: string;
            /** Spot */
            spot: string;
            /** Forward */
            forward: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    health_extended_api_v1_health_extended_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    price_api_v1_price_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PriceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PriceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    greeks_api_v1_greeks_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GreeksRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GreeksResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    implied_vol_api_v1_iv_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImpliedVolRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImpliedVolResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    latest_surface_api_v1_vol_surface_get: {
        parameters: {
            query?: {
                symbol?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SurfaceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    surface_at_api_v1_vol_surface_at__ts__get: {
        parameters: {
            query?: {
                symbol?: string;
            };
            header?: never;
            path: {
                ts: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SurfaceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    term_structure_api_v1_vol_term_structure_get: {
        parameters: {
            query?: {
                symbol?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TermStructureResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    smile_api_v1_vol_smile__tenor__get: {
        parameters: {
            query?: {
                symbol?: string;
            };
            header?: never;
            path: {
                tenor: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SmileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_positions_api_v1_positions_get: {
        parameters: {
            query?: {
                status?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PositionView"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_position_api_v1_positions__position_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                position_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    portfolio_risk_api_v1_risk_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GreeksAggregated"];
                };
            };
        };
    };
    pnl_curve_api_v1_pnl_curve_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PnLCurve"];
                };
            };
        };
    };
    position_history_api_v1_history_get: {
        parameters: {
            query: {
                position_id: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    signals_api_v1_signals_get: {
        parameters: {
            query?: {
                underlying?: string | null;
                tenor?: string | null;
                signal_type?: string | null;
                since?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignalRow"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    vol_history_api_v1_vol_history_get: {
        parameters: {
            query?: {
                symbol?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VolHistoryRow"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    backtests_api_v1_backtest_get: {
        parameters: {
            query?: {
                strategy_name?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestRunRow"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    system_stats_api_v1_system_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemStats"];
                };
            };
        };
    };
    state_api_v1_regime_state_get: {
        parameters: {
            query?: {
                symbol?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegimeStateOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    history_api_v1_regime_history_get: {
        parameters: {
            query?: {
                symbol?: string;
                n?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_events_api_v1_regime_events_get: {
        parameters: {
            query?: {
                n?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    insert_event_api_v1_regime_events_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    transitions_api_v1_regime_transitions_get: {
        parameters: {
            query?: {
                symbol?: string;
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    gmm_shadow_diagnostic_api_v1_regime_gmm_shadow_get: {
        parameters: {
            query?: {
                symbol?: string;
                n?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_events_from_feed_api_v1_regime_events_sync_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    state_api_v1_signals_pca_state_get: {
        parameters: {
            query?: {
                symbol?: string;
                /** @description if set, returns the named PcaModel.version instead of the active one (fixture mode for UI testing) */
                scenario?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    history_api_v1_signals_pca_history_get: {
        parameters: {
            query?: {
                symbol?: string;
                pc_id?: number;
                n?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    active_model_api_v1_signals_pca_model_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    refit_api_v1_admin_pca_refit_post: {
        parameters: {
            query?: {
                symbol?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_structures_api_v1_trade_structures_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
        };
    };
    list_limits_api_v1_trade_limits_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
    };
    get_book_api_v1_trade_book_get: {
        parameters: {
            query?: {
                symbol?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_preview_api_v1_trade_preview_post: {
        parameters: {
            query?: {
                symbol?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_preview_api_v1_trade_preview__preview_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                preview_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_preview_api_v1_trade_submit_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_submitted_structures_api_v1_trade_submitted_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_preview_api_v1_trade_preview__preview_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                preview_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_orders_api_v1_orders_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    place_order_api_v1_orders_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_order_api_v1_orders__order_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    live_positions_api_v1_exec_positions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    close_position_api_v1_exec_positions__con_id__close_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                con_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_active_api_v1_positions_active_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
        };
    };
    aggregate_greeks_api_v1_positions_aggregate_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_exit_rules_config_api_v1_positions_exit_rules_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
        };
    };
    list_delta_hedge_config_api_v1_positions_delta_hedge_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
        };
    };
    mtm_history_api_v1_positions__position_id__mtm_history_get: {
        parameters: {
            query?: {
                hours?: number;
                limit?: number;
            };
            header?: never;
            path: {
                position_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    position_alerts_api_v1_positions__position_id__alerts_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                position_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    position_hedges_api_v1_positions__position_id__hedges_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                position_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    signal_tracking_api_v1_positions__position_id__signal_tracking_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                position_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    close_manual_api_v1_positions__position_id__close_manual_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                position_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_monitor_once_api_v1_positions_monitor_run_once_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
